# Generated by Django 4.1 on 2022-08-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='punit_price',
            new_name='unit_price',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default='name', max_length=255),
        ),
    ]
