# Generated by Django 4.1 on 2022-08-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_punit_price_ingredient_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('KG', 'Kilogram'), ('G', 'Gram'), ('LB', 'Pound'), ('OZ', 'Ounce'), ('L', 'Liter'), ('ML', 'Mililiter'), ('P', 'Piece')], default='G', max_length=20),
        ),
    ]
